packaging_format = 2

id = "komga"
name = "Komga"
description.en = "Media server for your comics, manga and magazines"
description.fr = "Serveur multimédia pour vos bandes dessinées, mangas et magazines"

version = "1.12.1~ynh4"

maintainers = ["Navan Chauhan"]

[upstream]
license = "MIT"
website = "https://komga.org"
demo = "https://demo.komga.org"
admindoc = "https://komga.org/guides/"
code = "https://github.com/gotson/komga"

[integration]
yunohost = ">= 11.2.29"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/komga"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
        [resources.sources.main]
        url = "https://github.com/gotson/komga/releases/download/1.14.1/komga-1.14.1.jar"
        sha256 = "294345e933eaafce6b9bd5ce7286821ad2bc5477debd1160925fa54df24475b0"
        extract = false
        rename = "komga.jar"
        autoupdate.strategy = "latest_github_release"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    api.url = "/api"
    api.show_tile = false
    api.protected = true
    api.allowed = [ "visitors", "all_users" ]
    api.auth_header = false

    opds.url = "/opds"
    opds.show_tile = false
    opds.protected = false
    opds.allowed = [ "visitors", "all_users" ]
    opds.auth_header = false

    [resources.apt]
    packages = "openjdk-17-jre"
