# Only keep lines that are relevant to you!
# Lines starting with # are comments
# Make sure indentation is correct (2 spaces at every indentation level), yaml is very sensitive!
komga:
  config-dir: __DATA_DIR__/
  database:
    file: __DATA_DIR__/database.sqlite
  cors.allowed-origins:
    - http://127.0.0.1:__PORT__
  delete-empty-collections: true
  delete-empty-read-lists: true
server:
  port: __PORT__
  servlet:
    session.timeout: 7d # session timeout, here 7 days
    context-path: __PATH__/
